# NumPy Library Excercises

## Excercise 1:

Write a program that creates a unidimensional array with the positive integers smaller than
100 that are multiples of 4.

In [7]:
import numpy as np

my_array1 = np.arange(0, 100, 4)
print(my_array1)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


## Excercise 2:

Write a program that creates a bidimensional array of **5 rows and 4 columns** with the integers from **0 to 19**

In [8]:
import numpy as np

my_array2 = np.arange(20).reshape(5, 4)
print(my_array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


## Excercise 3:

Write a program that inverts the order of elements of a unidimensional array

In [9]:
import numpy as np

my_array3 = np.arange(20)
array_inverted = np.flip(my_array3)
print(array_inverted)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


## Excercise 4

Write a program that inverts the order of the rows of a bidimensional array

In [10]:
import numpy as np

my_array4 = np.arange(20).reshape(5, 4)
inverted_rows = np.flipud(my_array4)
print(my_array4)
print(f"\n{inverted_rows}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[16 17 18 19]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


## Excercise 5

Write a program that computes the mean of the elements of each column of a bidimensional array

In [11]:
import numpy as np

matriz = np.arange(1, 13).reshape(4, 3)

matriz = np.mean(matriz, axis=0)

print(matriz)

[5.5 6.5 7.5]


In [12]:
import numpy as np

# Instanciación manual dictando cada fila
matriz_manual = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Cálculo de la media colapsando el eje vertical (filas)
medias_manual = np.mean(matriz_manual, axis=0)

print("Matriz manual:\n", matriz_manual)
print("Medias por columna:", medias_manual)

Matriz manual:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Medias por columna: [5.5 6.5 7.5]


## Excercise 6

Write a program that reshapes a unidimensional array into a bidimensional array with 4 rows and 3 columns.

In [13]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
array_2d = np.reshape(array_1d, (4,3))
print(array_1d)
print("\n",array_2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
