# NumPy Library Excercises

## Excercise 1:

Write a program that creates a unidimensional array with the positive integers smaller than
100 that are multiples of 4.

In [21]:
import numpy as np

my_array1 = np.arange(0, 100, 4)
print(my_array1)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


## Excercise 2:

Write a program that creates a bidimensional array of **5 rows and 4 columns** with the integers from **0 to 19**

In [22]:
import numpy as np

my_array2 = np.arange(20).reshape(5, 4)
print(my_array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


## Excercise 3:

Write a program that inverts the order of elements of a unidimensional array

In [23]:
import numpy as np

my_array3 = np.arange(20)
array_inverted = np.flip(my_array3)
print(array_inverted)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


## Excercise 4

Write a program that inverts the order of the rows of a bidimensional array

In [4]:
import numpy as np

my_array4 = np.arange(20).reshape(5, 4)
inverted_rows = np.flipud(my_array4)
print(my_array4)
print(f"\n{inverted_rows}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[16 17 18 19]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


## Excercise 5

Write a program that computes the mean of the elements of each column of a bidimensional array

In [ ]:
import numpy as np

my_array5 = np.arange(20).reshape(5, 4)
